initiate Timeframe page to ask victim input start date and last interaction date.Last login: Fri Aug  9 10:24:09 on ttys002 Error checking TLS connection: Host is not running Agent pid 21109 Identity added: /Users/deyuanliu/.ssh/id_rsa (deyuan.liu@cds-snc.ca) Deyuans-MacBook-Pro:~ deyuanliu$ cd projects Deyuans-MacBook-Pro:projects deyuanliu$ cd frontend -bash: cd: frontend: No such file or directory Deyuans-MacBook-Pro:projects deyuanliu$ cd report-a-cybercrime/ Deyuans-MacBook-Pro:report-a-cybercrime deyuanliu$ cd frontend Deyuans-MacBook-Pro:frontend deyuanliu$ git checkout timeframepage frontend/src/Home.js: needs merge error: you need to resolve your current index first Deyuans-MacBook-Pro:frontend deyuanliu$ git status rebase in progress; onto c645cd1 You are currently rebasing branch 'timeframepage' on 'c645cd1'.   (fix conflicts and then run "git rebase --continue")   (use "git rebase --skip" to skip this patch)   (use "git rebase --abort" to check out the original branch)
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   src/p2/TimeFramePage.js
	new file:   src/p2/forms/TimeFrameInfoForm.js

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

	both modified:   src/Home.js

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	TimeFrameInfoForm.js

Deyuans-MacBook-Pro:frontend deyuanliu$ git rebase master
fatal: It seems that there is already a rebase-apply directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
	git rebase (--continue | --abort | --skip)
If that is not the case, please
	rm -fr ".git/rebase-apply"
and run me again.  I am stopping in case you still have something
valuable there.

Deyuans-MacBook-Pro:frontend deyuanliu$ git rebase (--continue | --abort | --skip)
-bash: syntax error near unexpected token `('
Deyuans-MacBook-Pro:frontend deyuanliu$ git stash apply
frontend/src/Home.js: needs merge
unable to refresh index
Deyuans-MacBook-Pro:frontend deyuanliu$ git status
rebase in progress; onto c645cd1
You are currently rebasing branch 'timeframepage' on 'c645cd1'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   src/p2/TimeFramePage.js
	new file:   src/p2/forms/TimeFrameInfoForm.js

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

	both modified:   src/Home.js

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	TimeFrameInfoForm.js

Deyuans-MacBook-Pro:frontend deyuanliu$ git add TimeFrameInfoForm.js
Deyuans-MacBook-Pro:frontend deyuanliu$ git add src/Home.js
Deyuans-MacBook-Pro:frontend deyuanliu$ git add src/p2/TimeFramePage.js src/p2/forms/TimeFrameInfoForm.js
Deyuans-MacBook-Pro:frontend deyuanliu$ git status
rebase in progress; onto c645cd1
You are currently rebasing branch 'timeframepage' on 'c645cd1'.
  (all conflicts fixed: run "git rebase --continue")

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   TimeFrameInfoForm.js
	modified:   src/Home.js
	new file:   src/p2/TimeFramePage.js
	new file:   src/p2/forms/TimeFrameInfoForm.js

Deyuans-MacBook-Pro:frontend deyuanliu$ git rebase --continue
Applying: unfinished p2 timeframe page
Deyuans-MacBook-Pro:frontend deyuanliu$ git status
On branch timeframepage
nothing to commit, working tree clean
Deyuans-MacBook-Pro:frontend deyuanliu$ git stash apply
Auto-merging frontend/src/Home.js
CONFLICT (content): Merge conflict in frontend/src/Home.js
Deyuans-MacBook-Pro:frontend deyuanliu$ git status
On branch timeframepage
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   src/p2/forms/TimeFrameInfoForm.js

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

	both modified:   src/Home.js

Deyuans-MacBook-Pro:frontend deyuanliu$ git add src/Home.js
Deyuans-MacBook-Pro:frontend deyuanliu$ git status
On branch timeframepage
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   src/Home.js
	modified:   src/p2/forms/TimeFrameInfoForm.js

Deyuans-MacBook-Pro:frontend deyuanliu$ git stash
Saved working directory and index state WIP on timeframepage: 1f45b4d unfinished p2 timeframe page
Deyuans-MacBook-Pro:frontend deyuanliu$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
Deyuans-MacBook-Pro:frontend deyuanliu$ git pull origin master
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), done.
From github.com:cds-snc/report-a-cybercrime
 * branch            master     -> FETCH_HEAD
   c645cd1..14b90f8  master     -> origin/master
Updating c645cd1..14b90f8
Fast-forward
 platform/base/kustomization.yaml | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
Deyuans-MacBook-Pro:frontend deyuanliu$ git checkout timeframe
error: pathspec 'timeframe' did not match any file(s) known to git
Deyuans-MacBook-Pro:frontend deyuanliu$ git checkout timeframepage
Switched to branch 'timeframepage'
Deyuans-MacBook-Pro:frontend deyuanliu$ git rebase master
First, rewinding head to replay your work on top of it...
Applying: unfinished p2 timeframe page
Deyuans-MacBook-Pro:frontend deyuanliu$ git stash apply
On branch timeframepage
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/Home.js
	modified:   src/p2/forms/TimeFrameInfoForm.js

no changes added to commit (use "git add" and/or "git commit -a")
Deyuans-MacBook-Pro:frontend deyuanliu$ git commit
husky > pre-commit (node v12.4.0)

> rcmp-prototype-api@1.0.0 print-schema /Users/deyuanliu/projects/report-a-cybercrime/api
> bin/print-schema > schema.graphql && git add ./schema.graphql

   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │       New minor version of npm available! 6.9.0 → 6.10.3       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.10.3   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

On branch timeframepage
Changes not staged for commit:
	modified:   src/Home.js
	modified:   src/p2/forms/TimeFrameInfoForm.js

no changes added to commit
Deyuans-MacBook-Pro:frontend deyuanliu$ git add src/Home.js src/p2/forms/TimeFrameInfoForm.js
Deyuans-MacBook-Pro:frontend deyuanliu$ git commit
husky > pre-commit (node v12.4.0)

> rcmp-prototype-api@1.0.0 print-schema /Users/deyuanliu/projects/report-a-cybercrime/api
> bin/print-schema > schema.graphql && git add ./schema.graphql

Aborting commit due to empty commit message.
timeframepage.js not finished yet
Deyuans-MacBook-Pro:frontend deyuanliu$ git status
On branch timeframepage
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   src/Home.js
	modified:   src/p2/forms/TimeFrameInfoForm.js

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/p2/LandingPage.js
	modified:   src/p2/TimeFramePage.js

Deyuans-MacBook-Pro:frontend deyuanliu$ git add src/Home.js src/p2/forms/TimeFrameInfoForm.js
Deyuans-MacBook-Pro:frontend deyuanliu$ git commit
husky > pre-commit (node v12.4.0)

> rcmp-prototype-api@1.0.0 print-schema /Users/deyuanliu/projects/report-a-cybercrime/api
> bin/print-schema > schema.graphql && git add ./schema.graphql

[timeframepage 9cd6a7f] timeframepage.js not finished yet
 Committer: Deyuan Liu <deyuanliu@Deyuans-MacBook-Pro.local>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 2 files changed, 234 insertions(+), 15 deletions(-)
Deyuans-MacBook-Pro:frontend deyuanliu$ git push
fatal: The current branch timeframepage has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin timeframepage

Deyuans-MacBook-Pro:frontend deyuanliu$ git push --set-upstream origin timeframepage
Enumerating objects: 23, done.
Counting objects: 100% (23/23), done.
Delta compression using up to 4 threads
Compressing objects: 100% (16/16), done.
Writing objects: 100% (17/17), 3.43 KiB | 1.14 MiB/s, done.
Total 17 (delta 11), reused 1 (delta 0)
remote: Resolving deltas: 100% (11/11), completed with 5 local objects.
remote:
remote: Create a pull request for 'timeframepage' on GitHub by visiting:
remote:      https://github.com/cds-snc/report-a-cybercrime/pull/new/timeframepage
remote:
To github.com:cds-snc/report-a-cybercrime.git
 * [new branch]      timeframepage -> timeframepage
Branch 'timeframepage' set up to track remote branch 'timeframepage' from 'origin'.
Deyuans-MacBook-Pro:frontend deyuanliu$ git checkout -b contactinfopage
M	frontend/src/p2/LandingPage.js
M	frontend/src/p2/TimeFramePage.js
Switched to a new branch 'contactinfopage'
Deyuans-MacBook-Pro:frontend deyuanliu$ git checkout timeframepage
M	frontend/src/p2/LandingPage.js
M	frontend/src/p2/TimeFramePage.js
Switched to branch 'timeframepage'
Your branch is up to date with 'origin/timeframepage'.
Deyuans-MacBook-Pro:frontend deyuanliu$ git status
On branch timeframepage
Your branch is up to date with 'origin/timeframepage'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/p2/LandingPage.js
	modified:   src/p2/TimeFramePage.js
	modified:   src/p2/forms/TimeFrameInfoForm.js

no changes added to commit (use "git add" and/or "git commit -a")
Deyuans-MacBook-Pro:frontend deyuanliu$ npm run extract

> report-a-cybercrime@0.0.1 extract /Users/deyuanliu/projects/report-a-cybercrime/frontend
> lingui extract

Catalog statistics:
┌─────────────┬─────────────┬─────────┐
│ Language    │ Total count │ Missing │
├─────────────┼─────────────┼─────────┤
│ en (source) │     173     │    -    │
│ fr          │     165     │    5    │
└─────────────┴─────────────┴─────────┘

(use "npm run add-locale <locale>" to add more locales)
(use "npm run extract" to update catalogs with new messages)
(use "npm run compile" to compile catalogs for production)
Deyuans-MacBook-Pro:frontend deyuanliu$ npm run check-translations

> report-a-cybercrime@0.0.1 check-translations /Users/deyuanliu/projects/report-a-cybercrime/frontend
> lingui extract && node utils/checkTranslations.js

Catalog statistics:
┌─────────────┬─────────────┬─────────┐
│ Language    │ Total count │ Missing │
├─────────────┼─────────────┼─────────┤
│ en (source) │     173     │    -    │
│ fr          │     165     │    0    │
└─────────────┴─────────────┴─────────┘

(use "npm run add-locale <locale>" to add more locales)
(use "npm run extract" to update catalogs with new messages)
(use "npm run compile" to compile catalogs for production)
Deyuans-MacBook-Pro:frontend deyuanliu$ git status
On branch timeframepage
Your branch is up to date with 'origin/timeframepage'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   locale/en/messages.json
	modified:   locale/fr/messages.json
	modified:   src/p2/LandingPage.js
	modified:   src/p2/TimeFramePage.js
	modified:   src/p2/forms/TimeFrameInfoForm.js

no changes added to commit (use "git add" and/or "git commit -a")
Deyuans-MacBook-Pro:frontend deyuanliu$ git add locale/en/messages.json locale/fr/messages.json src/p2/TimeFramePage.js src/p2/forms/TimeFrameInfoForm.js
Deyuans-MacBook-Pro:frontend deyuanliu$ git status
On branch timeframepage
Your branch is up to date with 'origin/timeframepage'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   locale/en/messages.json
	modified:   locale/fr/messages.json
	modified:   src/p2/TimeFramePage.js
	modified:   src/p2/forms/TimeFrameInfoForm.js

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
initiate Timeframe page to ask victim input start date and last interaction date.
~
~
~
~
~
~
~
~
-- INSERT --